apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      name: grafana
      labels:
        app: monitoring
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafa-datasources
          moountPath: /etc/grafana/provisioning/datasources
          readOnly: false
    volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: grafana-datasources
        configMap:
            defaultMode: 420
            name: grafana-datasources
