apiVersion: v1
kind: Service
metadata:
  name: demo-app-be-svc
spec:
  type: ClusterIP
  selector:
    app: demo-app
    tier: backend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
      tier: backend
  template:
    metadata:
      labels:
        app: demo-app
        tier: backend
    spec:
      containers:
      - name: be-app
        image: kubernautslabs/to-do-app-backend
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        env:
          - name: DB_HOST  # Setting DB host address from configMap
            valueFrom:
              configMapKeyRef:
                key: host
                name: db-conf
          - name: DB_NAME # Setting DB name from configMap
            valueFrom:
              configMapKeyRef:
                key: name
                name: db-conf
          - name: DB_USERNAME # Setting DB user from Secret
            valueFrom:
             secretKeyRef:
                key: username
                name: db-credentials
          - name: DB_PASSWORD # Setting DB password from Secret
            valueFrom:
              secretKeyRef:
                key: password
                name: db-credentials
        ports:
        - containerPort: 8080

