apiVersion: v1
kind: Service
metadata:
  name: demo-app-fe-svc
spec:
  type: ClusterIP
  selector:
    app: demo-app
    tier: fe
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deploy
  labels:
    app: demo-app
    tier: fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
      tier: fe
  template:
    metadata:
      labels:
        app: appname
        tier: fe
    spec:
      containers:
      - name: fe-app
        image: kubernautslabs/to-do-app-frontend
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "300m"
        env: # Setting Env Variables
          - name: SERVER_URI # Setting BE URI from configMAP
            valueFrom:
              configMapKeyRef:
                name: backend-conf # Name of configMap
                key: server-uri
        ports:
        - containerPort: 8080
