apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopui
  template:
    metadata:
      labels:
        app: shopui
    spec:
      containers:
      - name: shopui
        image: devteds/demo-bookstore-shopui:1.0
        ports:
        - containerPort: 80
