apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopapi-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopapi
  template:
    metadata:
      labels:
        app: shopapi
    spec:
      containers:
      - name: shopapi
        image: devteds/demo-bookstore-shopapi:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        volumeMounts:
          - mountPath: /app/config/app_secret
            name: secret-vol
        envFrom:
          - configMapRef:
              name: shopapi-cm
      volumes:
        - name: secret-vol
          secret:
            secretName: shopapi-sec
